title: participative press
email: //
description: simple blog with opinions about art & culture 
#baseurl: "participativepress"
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  participativepress

